### ISSUE TITLE
RDM pattern_descriptors- not auto generated

### ISSUE THREAD

**Issue by saarbuckle** [rsagroup/rsatoolbox#123]
The RDM pattern_descriptors field seems to be incorrect in its current form. There should be one descriptor per RDM value, and ideally they contain info about the condition pair (e.g. condition 1 vs 2) that the according dissimilarity value in the RDM reflects. However, these are not auto-generated, and instead contain an index of size # conditions. 

I don't think the user should be responsible for generating these descriptors. Thoughts?

**Comment by HeikoSchuett** [comment]
Well the descriptors as they are right now are intended as descriptors per pattern/stimulus, not per pair. That is intended.

Do you need these pair_descriptors you describe somewhere?

**Comment by saarbuckle** [comment]
Ah I see, thanks Heiko! Are these necessary in the rdm object? My confusion originated with the intended size descried in `rdms.py` under pattern_descriptors, where they are noted as descriptors with 1 value per RDM column (since each column is a dissimilarity value, not a pattern per-se). Is there a reason these descriptors are named something different than the same field in the dataset object (obs_descriptor)?

I don't need the pair_descriptors for anything at the moment.

**Comment by HeikoSchuett** [comment]
Hi! they can be something different than the obs_descriptors as often more than one observation can enter the pattern estimate for one pattern. 

As the description was confusing: Feel free to change it with your documentation updates! It was meant to mean row/column of the actual matrix.
