### ISSUE TITLE
Readthedocs build fails because of notebook memory use

### ISSUE THREAD

**Issue by JasperVanDenBosch** [rsagroup/rsatoolbox#134]
```
reading sources... [ 12%] exercise_all


Command killed due to excessive memory consumption
```

It ran before so the new changes must have made it heavier perhaps

**Comment by JasperVanDenBosch** [comment]
Note that RTD is a free service and therefore runs our builds on cheap low-ish-memory virtual machines. So there's a few solutions:

1. reduce the memory usage of our notebooks (smaller data samples)
2. give up including (some or all) notebooks in the documentation
3. host the documentation on our own hosted site (but this requires some money) 

Here's the limits (3GB, 15mins): https://docs.readthedocs.io/en/stable/builds.html

**Comment by jooh** [comment]
Would it make sense to put pre-rendered notebooks in the repo for RTD, and run the actual notebook code execution test as part of the Travis code tests instead? See also #142 

Depends on if you think of notebooks as code or docs I guess.

**Comment by JasperVanDenBosch** [comment]
It seems that it now usually works again:
![builds](https://user-images.githubusercontent.com/1508492/95448956-5e652a80-0964-11eb-8ed7-6ef1a72a9158.png)

I think pre-rendering the notebooks sounds good but I haven't found a tool yet to easily do that and integrate the resulting html

edit
The one thing I did find was to use symbolic links to the notebook html but that doesn't sound all that reliable to me

**Comment by HeikoSchuett** [comment]
I think this only occurred because of a bug in the RDM calculation, which was fixed since then. Shall we close this for now as currently everything works fine?

**Comment by JasperVanDenBosch** [comment]
Let's wait until we merge #184, if that renders then we can definitely close this

**Comment by HeikoSchuett** [comment]
it looks like the readthedocs were failing for a while longer and didn't try recently. Can you check whether it works now? #184 is merged now, too

**Comment by JasperVanDenBosch** [comment]
```
updating environment: 40 added, 0 changed, 0 removed
reading sources... [  2%] comparing
reading sources... [  5%] datasets
reading sources... [  7%] demos
reading sources... [ 10%] distances
reading sources... [ 12%] exercise_all


Command killed due to excessive memory consumption
```

**Comment by JasperVanDenBosch** [comment]
The last successful build was 5 months ago

**Comment by JasperVanDenBosch** [comment]
Fixed configuration and it seems to work now
