### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Jiashun97** [rsagroup/rsatoolbox#154]
Has anyone encounter the ImportError when trying to import pyrsa?
![error](https://user-images.githubusercontent.com/65221219/96388401-da534400-11a8-11eb-8c34-6f38d981f9f6.png)

**Comment by HeikoSchuett** [comment]
Hi, I have not seen this error before, no. Could you provide the stack trace for this?

**Comment by JasperVanDenBosch** [comment]
Looks like a version conflict. We should probably pin the scikit-learn
version

**Comment by Jiashun97** [comment]
> Hi, I have not seen this error before, no. Could you provide the stack trace for this?

![Screen Shot 2020-10-19 at 12 52 16](https://user-images.githubusercontent.com/65221219/96441524-ee7b5d80-1209-11eb-98ef-20c3cb67f89d.png)

**Comment by JasperVanDenBosch** [comment]
Try `pip install -U scikit-learn`

**Comment by Jiashun97** [comment]
> Try `pip install -U scikit-learn`

Got this after tried the installation.

![Screen Shot 2020-10-19 at 13 20 56](https://user-images.githubusercontent.com/65221219/96444095-f210e380-120d-11eb-83ad-dcc3e6ae36ff.png)

**Comment by JasperVanDenBosch** [comment]
`pip install -U Pillow`

**Comment by Jiashun97** [comment]
Thank you so much. It works now!

**Comment by JasperVanDenBosch** [comment]
Great! Feel free to open a new issue if you encounter another problem
