### ISSUE TITLE
Errors in the "exercise_all" DEMO

### ISSUE THREAD

**Issue by Jiashun97** [rsagroup/rsatoolbox#156]
Hi, I encountered a KeyError in the "exercise_all" DEMO when I am trying to to set train_set, test_set, and ceil_set for the cross-validation regarding flexible models. Could you have a look at this? Thanks.
![Screen Shot 2020-10-20 at 02 01 32](https://user-images.githubusercontent.com/65221219/96524458-a47d9080-1278-11eb-8367-c18e2699f369.png)

**Comment by HeikoSchuett** [comment]
This was an error with a missing default value for the descriptor. I think this was fixed with #117 . 
I.e. if you update to a newer version this error should go away! If it does not, please open a new issue!
