### ISSUE TITLE
Basing data classes on pandas.DataFrame or xarray.DataArray

### ISSUE THREAD

**Issue by jooh** [rsagroup/rsatoolbox#160]
The project currently contains data classes that are constructed from scratch, with raw numpy arrays to store data and associated dicts for keeping track of meta data. This results in a lot of re-inventing the wheel when it comes to e.g. supporting indexing (see #130) or keeping track of meta data over operations. This kind of stuff is already implemented in a performant and well-tested way in pandas. Is there any interest in adopting this for pyrsa?

Concretely, there are a few ways to do this. We could just use composition, so convert existing data array attributes to dataframes with the descriptor dicts as column labels (we might still want to expose these dicts in the objects but they would not be constructed by quering the DataFrame). Or we could [register the RSA-specific properties and methods as a custom accessor](https://pandas.pydata.org/pandas-docs/stable/development/extending.html). So for instance, the rdm.RDMs object would end up a pandas.DataFrame, but with its current methods and properties in a `df.rdm` attribute. One appealing thing about the latter accessor approach is that our data crunching tools would end up taking DataFrames as input, which makes it a lot easier to combine pyrsa with other data libraries in an analysis pipeline.

There is a learning curve associated with using pandas, especially if you're coming at this from Matlab. But there are huge benefits in terms of offloading complexity to a supporting library, increasing performance, and gaining access to panda's rich feature set.

Would be happy to work a bit on this with e.g. rdm.RDMs as a test case. But it's quite a bit of work so before I do so I wanted to first gauge if there's any interest.

**Comment by JasperVanDenBosch** [comment]
Thanks for thinking about this Johan -  I agree it's good to think about how we structure things.

A few thoughts:

I do like pandas for table-like data. But I'm not sure it's the right fit to replace all our data structures. I've come across a few obscure bugs here and there with it, and have contributed code to the project, and was not particularly impressed with how it's maintained. I also have doubts about the performance aspect - something that we expect to be quite important for pyrsa down the road.

I'm not as familiar with xarray so can't say much about that.

One thing I've been thinking to do for a while; but this is more about the outside than the inside I suppose; is to have wrapper functionality which exposes a pure-array (numpy I was thinking) API. Something like

```python
from pyrsa.ndarray import calc_rdm
rdm_vectors = calc_rdm(data)
```

where both `data` and `rdm_vectors` are simple numpy arrays. `pyrsa.ndarray.calc_rdm` (or a better name) would then make the objects and call the methods internally. This would expose an interface that may be more accessible for certain users.

**Comment by HeikoSchuett** [comment]
Hi! Yes, it is always good to have someone else look at the actual implementation of things! 

I mostly agree with Jasper. It definitely seemed easier to write these objects from scratch than tweaking existing ones to meet our needs when we started this. Especially having multiple descriptors/label vectors for multiple dimensions and the RDM type of data which corresponds to only half of a matrix which the descriptors refer to are hard. Also that is definitely stuff which is not super easily added to a data frame or xarray. Also, now that we have them it is very easy to add anything we might need additionally.

Nonetheless, I think we would prefer an improved version of these objects based on another structure at its hard like an xarray or a data-frame if this worked better. It would have to be mostly a refactoring though, i.e. a replacement behind the scenes which does not affect how the objects look to the rest of the toolbox, as all functions the objects provide are necessary.

Making our usual functions work with numpy arrays as input (or anything which simply converts with np.array(input) as data frames and xarray do) would definitely be good I think.

**Comment by iancharest** [comment]
This is very good thoughts.

+1 for the functionality allowing passing data as simple numpy arrays!

Cheers!

ian

**Comment by caiw** [comment]
I tend to agree that re-inventing the wheel is best only as a last resort.  Efficient by-reference slicing and function broadcasting aren't trivial, and would be provided "for free" by making `RDMs` delegate this to an established library.  Plus we'd get to let other people worry about weird edge-cases :)

Having said that, I've found pandas to be a bit cumbersome and idiosyncratic when it comes to actually doing things beyond filter/reduce operations, or with data which is naturally high-dimensional.  But perhaps I just don't have the knack with it.

Does anyone have hands-on experience with xarray?

**Comment by JasperVanDenBosch** [comment]
We've now come so far that it's safe to say we'll stick with the current approach for internal structure for a while.
As for an additional, functional interface, that should be a separate issue: #160
