### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by caiw** [rsagroup/rsatoolbox#169]
[Git has acknowledged](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) that old default branch name of "`master`" is offensive – and thus exclusionary – to some people, due to its obvious association with slavery.  As such, the general approach has been to change the primary branch name to `main`, which is both neural in this regard, and also more technically appropriate. In fact, this will be Git's and GitHub's default behaviour in future.

In the spirit of open science and open source, **I suggest we rename `master` to `main`** for this repository.  People's forks upstream tracking will need to be updated, but I think this [small amount of inconvenience](https://www.techrepublic.com/article/github-to-replace-master-with-main-starting-in-october-what-developers-need-to-know/) now, while the project is young, is worth the long term benefits of being more inclusive, and not standing out as old-fashioned in the years to come.

As a side note, I encourage everyone to follow this practice in their own repositories. The muscle memory is not that hard to re-learn, and the small effort we will collectively expend to do so will encourage us to be more thoughtful about naming and language in general.

**Comment by HeikoSchuett** [comment]
I just did the renaming. The lines to change the name in your local copy are:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by caiw** [comment]
Thanks @HeikoSchuett!
