### ISSUE TITLE
`concat(rdms)` should be able to accept multiple RDMs as arguments

### ISSUE THREAD

**Issue by caiw** [rsagroup/rsatoolbox#170]
It would be nice (and expected?) to be able to write
```python
rdms = concat(rdms1, rdms2, rdms3)
```
instead of 
```python
rdms = concat((rdms1, rdms2, rdms3))
```
This can be easily achieved by changing the signature of `concat` to `concat(*rdms)`, and doing a little check to ensure lists can still be passed.

**Comment by HeikoSchuett** [comment]
Yes, this sounds sensible. I guess the best variant would be it both work to still allow `concat(list_of_rdms)`. 

If you have the time to do this the fastest way to add this to the toolbox would be if you open a small pull request which changes this. This change should not require any other changes I think.
I promise to check & merge it quickly if you implement this!

**Comment by caiw** [comment]
@HeikoSchuett There you go! :)
