### ISSUE TITLE
Usage of whitened unbiased RDM cosine similarity (WUC)?

### ISSUE THREAD

**Issue by charlesbmi** [rsagroup/rsatoolbox#175]
I recently read "[Comparing representational geometries using whitened unbiased-distance-matrix similarity](https://arxiv.org/abs/2007.02789)" and saw that it recommends whitening data RDMs before calculating the cosine similarity.

Does `pyrsa.rdm.compare(rdm1, rdm2, 'cosine_cov', sigma_k=None)` whiten the data RDMs appropriately by default? If not, should I just take the standard covariance over the `(n_rdm, n_pattern_pairs)` RDMs matrix? I wasn't sure if I should be using the variances from the estimating the crossnobis distances (for the RDMs) or if there is a helper function for this.

Thanks!

**Comment by HeikoSchuett** [comment]
Hi there, 

yes these functions do whiten the rdms, that is the only difference between them and the normal cosine and corr compare functions. The sigma_k actually corresponds to the sigma_k in the paper, i.e. if you want to set it it should be (an estimate of) the noise covariance over patterns. If you do not pass a sigma_k, it assumes iid measurements for the different patterns. As we describe in the manuscript this is different from assuming iid distances and already better and sufficient for many conditions as long as you can assume independent measurements for the different patterns/conditions/stimuli.

**Comment by charlesbmi** [comment]
Thanks Heiko! That's helpful.
