### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by JasperVanDenBosch** [rsagroup/rsatoolbox#177]
Should we (gradually) introduce type annotations? In recent python versions you can do:

```
def sum(a: int, b:int): -> int
    return a + b
```

and a tool such as _mypy_ or _pylance_ will check your code for violations while you're typing, often 
pointing out bugs based on expectations of what another component will do.
My proposal is that from henceforth, contributors who want to, may add such annotations.

**Comment by JasperVanDenBosch** [comment]
This would mean dropping support for python 3.6 which will be EOL in 6 months: https://endoflife.date/python

**Comment by jooh** [comment]
All in favour of type annotations here. Are there any important libraries that are still 3.6 only?

**Comment by JasperVanDenBosch** [comment]
That's a good question. From what I can find; numpy, scipy, matplotlib, scikit-learn and scikit-image all follow [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html), a policy which requires them to support recent python versions and drop support for versions older than 42 months.
For our depencies that leaves [joblib](https://pypi.org/project/joblib/), [h5py](https://travis-ci.org/github/h5py/h5py/jobs/766775179/config) (python versions not listed but uses 3.7 for their CI) and [tqdm](https://pypi.org/project/tqdm/), which all seem to support 3.7.

**Comment by jooh** [comment]
Also just noticed that numpy added type annotations very recently in release 1.20, February 2021. Very useful for us given number of numpy arrays going around.
