### ISSUE TITLE
Documentation of distance measures - squared vs non-squared distances

### ISSUE THREAD

**Issue by Tal-Golan** [rsagroup/rsatoolbox#179]
As a user of the toolbox, I find it misleading that 'euclidian distance' is the squared euclidean distance (divided by the number of channels). I suggest changing the documentation of `calc_rdm_euclid`, `calc_rdm_mahalanobis` and `calc_rdm_crossnobis` to reflect the computed distance function more precisely. This will ensure that future users don't incorrectly report the distance measures they've employed.

**Comment by HeikoSchuett** [comment]
Thanks for notifying us Tal! We shall have a look at better documentation anyway and will fix this.
