### ISSUE TITLE
Bootstrapping against 

### ISSUE THREAD

**Issue by charlesbmi** [rsagroup/rsatoolbox#183]
Is there a way to compare two groups of RDMs against each other (instead of 1 group of RDMs against a single-RDM model)? To take the example of [Ejaz, Hamada, and Diedrichsen (2015)](https://www.nature.com/articles/nn.4038) say I wanted to quantify the similarity between the representational structures from fMRI recordings (with multiple subjects) and EMG recordings (with multiple subjects).

In the original paper, the authors collapse the EMG recordings to a single-RDM average model ([Fig 5d](https://www.nature.com/articles/nn.4038/figures/5)), then describe that this is a reasonable approach because the EMG RDMs are fairly consistent. This seems solid, but perhaps it would be even better to bootstrap over both fMRI and EMG RDMs?

I couldn't tell if this was already supported within pyrsa and/or this is a reasonable approach. Thanks for the help!

**Comment by JasperVanDenBosch** [comment]
I suppose that depends on the type of test you'd perform on the bootstrapped distribution. If you consider the EMG and fMRI to be a paired sample, then you could bootstrap the difference RDM

**Comment by HeikoSchuett** [comment]
I agree with @ilogue here.
To answer to your questions directly: Yes, that seems like a reasonable idea. We do not implement something like this in the toolbox yet.

The main question you should ask yourself for this is which bootstrap resampling scheme is adequate for the sampling in the actual experiment and the generalization you want to achieve. If the RDMs are paired, i.e. each subject contributes a RDM to each group, then you should resample taking both RDMs in or out. If you assume that the stimuli are a random sample from a population you want to generalize to you need to resample the stimuli as well etc.

**Comment by charlesbmi** [comment]
Thanks ilogue and Heiko! That makes sense. In my case, the RDMs are from different subjects (not paired), so I will bootstrap across each group separately.
