### ISSUE TITLE
show_rdm figures broken in docs due to missing rdms.mplstyle

### ISSUE THREAD

**Issue by jooh** [rsagroup/rsatoolbox#192]
Looks like vis.show_rdm is broken in the docs because the rdms.mplstyle file is missing from the build context. Happy to fix if someone can point to where it needs to be added in.

See e.g. https://rsatoolbox.readthedocs.io/en/latest/demo_rdm_vis.html#Plotting-RDMs-with-text-labels

**Comment by JasperVanDenBosch** [comment]
same as #191 

yeah I have to figure out how to include these and get them in the right place

**Comment by HeikoSchuett** [comment]
It looks to me like the mplstyle file is simply not installed with the rest of the code. The python packaging seems to suggest to use a `MANIFEST.in` file defining that this file should also be copied.

[https://python-packaging.readthedocs.io/en/latest/non-code-files.html](https://python-packaging.readthedocs.io/en/latest/non-code-files.html)
