### ISSUE TITLE
If RDM contains NaN, return NaN instead of Error

### ISSUE THREAD

**Issue by smazurchuk** [rsagroup/rsatoolbox#211]
Thanks for making this toolbox. I was wondering if people would be open to changing the behavior of the `_parse_input_rdms` function. Often when doing searchlight analysis, `NaNs` get introduced into some patches. At present the `evaluate_models_searchlight` function raises an error (and stops) if it encounters a NaN. Could we change this behavior to simply add an extra option to `evaluate_searchlight` function to return a NaN vertex value at patches that contain NaNs?

Thanks

https://github.com/rsagroup/rsatoolbox/blob/ead07b256aad5005c883b6fba3cd50c7417bbcf9/rsatoolbox/rdm/compare.py#L520

**Comment by HeikoSchuett** [comment]
apparently @ilogue  will have a look at that. Changing this behavior certainly seems sensible.

I think we might want to keep the check in the `_parse_input_rdms` because it checks whether RDMs that have both NaNs and finite values as entries are compatible. It seems better to me to catch the NaN inducing positions already in the searchlight or compare functions, such that they immediately return `NaN` before starting any computation about the RDMs.

**Comment by smazurchuk** [comment]
Very cool! Thanks for checking this out. I just started using the toolbox. While changing the NaN behavior would be helpful, is there any discussion/interest in improving the performance of the toolbox for searchlight analysis?

I've been unable to get a searchlight analysis down to a reasonable time (even having tried multithreading and multi-process approaches). Linked is a jupyter-notebook I put together to show that I think a key place that could drastically speed up the toolbox is optimizing the `split_obs` function. It is used very often and depends on a list comprehension. I think it might be possible to change this to also accept a numpy boolean vector (or numpy array for fancy indexing)

https://github.com/smazurchuk/general/blob/master/rsa_timing.ipynb

Thanks again! Let me know if this is a direction people are interested in moving.

**Comment by HeikoSchuett** [comment]
I'll have a look at the timing issue. Making the subsetting faster would benefit all analyses in the toolbox, so that is certainly worth a bit of effort.

**Comment by HeikoSchuett** [comment]
Ok, so I had a bit of a look at the timing stuff and think I managed to remove a bit of the baggage which comes from copying around the descriptors of the data everywhere. 

I was not entirely sure how many channels your dataset has, so I set it to 100. With that number of channels I would now be at ~100ms for computing one cross-nobis RDM based on cross validating the 6 runs for 300 patterns, i.e. I ran the following code:

```
import cProfile as profile
import numpy as np
import rsatoolbox


dat = np.random.randn(1800, 100)
data = rsatoolbox.data.Dataset(
    dat,
    obs_descriptors={'obs': np.repeat(np.arange(300), 6),
                     'rep': np.repeat(np.arange(6), 300).reshape(
                         6, 300).transpose().flatten()}
    )

profile.run("rsatoolbox.rdm.calc_rdm_crossnobis(data,'obs',cv_descriptor='rep')", sort='cumtime')

```
and got the following response:
`56506 function calls (56439 primitive calls) in 0.096 seconds`


This is a lot better than 10 per minute already. I'll check on the actual searchlight code as well to make sure that it does not run into similar speed issues elsewhere.

**Comment by JasperVanDenBosch** [comment]
Excellent, great work @HeikoSchuett on the speedup. I mostly assigned myself a a reminder for myself that I wanted to have a look as I agree with you it would be good to allow NaNs.

@smazurchuk do you think you could give it a go yourself perhaps? You're very welcome to open a pull request. Let me know if I can assist with that in any way. I'm not sure I'll get around to building something myself this week

**Comment by smazurchuk** [comment]
Wow! Thanks @HeikoSchuett !! That was very quick work. It's very appreciated. @ilogue I'm happy to help too but I'm a bit new to working on such a collaborative project, so it might take a bit before I open that pull request. Thanks!

**Comment by smazurchuk** [comment]
Just closing this issue as it was ultimately decided that best practice would probably be to deal with the NaN's prior to searchlight analysis

**Comment by andreifoldes** [comment]
Sorry this might seem like a stupid question by I'm also running a searching using the toolbox and don't understand how there can be NaNs in dissimilarity matrix if the beta-maps don't have any NaNs?
