### ISSUE TITLE
Implement dataset 3D handling

### ISSUE THREAD

**Issue by HeikoSchuett** [rsagroup/rsatoolbox#22]
integrates the TODOs from dataset.py

**Comment by HeikoSchuett** [comment]
As a question on how to implement splitting etc.: Are we going to return a list of dataset objects or a 3D dataset by default? both would work

**Comment by doerlbh** [comment]
As discussed and seconded in pull request #16 , the current decision is to return a DatasetList or DatasetSequence class object with the base of a list of dataset objects. The 3D handling task is currently a low-priority task which will be further developed in the next iteration. Thanks for starting the thread.

**Comment by doerlbh** [comment]
The 3D option is removed from the current development and will be future included in the DatasetList implementation including principled operations such as sliding window.
