### ISSUE TITLE
Colormap unification

### ISSUE THREAD

**Issue by HeikoSchuett** [rsagroup/rsatoolbox#232]
We talked last time about a unification fo the colormaps used in the toolbox. We certainly want to keep the option for users to choose their own colormaps of course, but by default we should have a reasonably consistent setting

**Comment by JasperVanDenBosch** [comment]
let's also look at this deprecation
```
/rsatoolbox/env/lib/python3.10/site-packages/rsatoolbox/vis/icon.py:246: PendingDeprecationWarning: The get_cmap function will be deprecated in a future version. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead.
    im = cm.get_cmap(self.cmap)(im)
```

**Comment by JasperVanDenBosch** [comment]
luminance 0->max
default map but options

**Comment by JasperVanDenBosch** [comment]
send around some options as a colorbar+sample RDM
