### ISSUE TITLE
calc_rdm_crossnobis changes data structure

### ISSUE THREAD

**Issue by jdiedrichsen** [rsagroup/rsatoolbox#237]
calc_rdm_crossnobis actually changes the data structure that the user passes to it. 
On line 305 (rsa.rdm.calc.py) 
dataset.sort_by(descriptor)

The data set is sorted (in place) by descriptor. 

This is very unecexpected and undesirable behavior, as the user may rely in downstream processing that the data is sorted in a specific way. I believe it is also very likely unecessary. 

@HeikoSchuett : Are you maintaining this function? 
Can we change it to ensure the passed data structure is not changed?

**Comment by HeikoSchuett** [comment]
Hi @jdiedrichsen,
thanks for noticing!
yes this is definitely not intended. I remember faintly that the sorting had a purpose towards making the cross-validation splits align with the patterns, but I'll check whether we need the sorting in the current version.
If in doubt we can copy the dataset, i.e. there will be a way to not change the input.

**Comment by HeikoSchuett** [comment]
Ok, I checked and the sort is necessary if different runs have the conditions in a different order.
I fixed the side effect by initially copying the dataset object. If this seems fine to you, please review the pull request I just opened! 
Thanks again for finding this!

**Comment by jdiedrichsen** [comment]
Ok - will do. With some more time we probably should review whether sorting is necessary (seems inefficient and possibly unstable), but for now a simple fix will do.
