### ISSUE TITLE
Implement DatasetList options (including sliding window operations)

### ISSUE THREAD

**Issue by doerlbh** [rsagroup/rsatoolbox#24]
As discussed and seconded in pull request #16 , one design decision is to have a supplementary class called DatasetList object with the base of a list of dataset objects. This include implementation of other principled segmentation operations such as sliding window for dynamic analysis.

**Comment by eberlot** [comment]
My understanding is that the DatasetList object should really be dealing with the dataset (2 / 3D) as provided (and possible splits / subsets). I can see that a sliding window analysis would be incorporated down the line, but I'm not sure this would be the most fitting place for it. It'd be good to hear thoughts of others.

**Comment by doerlbh** [comment]
> My understanding is that the DatasetList object should really be dealing with the dataset (2 / 3D) as provided (and possible splits / subsets). I can see that a sliding window analysis would be incorporated down the line, but I'm not sure this would be the most fitting place for it. It'd be good to hear thoughts of others.

Thanks for the input! FYI, in the current setup, dataset is only allowed to be 2D. I think DatasetList could be a useful wrapper class to include additional extra dimension information, also as you pointed out, the current subset and splits are already outputting a list of Dataset, which could be later wrapped as a DatasetList. All discussions are welcome! 

BTW, this line of implementation will not included until the current pull request #16 is approved and merged, to avoid too heavy reviewing pressure.

**Comment by Tal-Golan** [comment]
Switching `measurements` from a numpy array to an xarray DataArray can allow Dataset to represent arbitrary N-D array data without considerably changing the existing code. http://xarray.pydata.org/en/stable/
