### ISSUE TITLE
Yet another searchlight runtime warning

### ISSUE THREAD

**Issue by jones-michael-s** [rsagroup/rsatoolbox#254]
Getting an invalid multiplication warning during `evaluate_models_searchlight`

```
Evaluating models for each searchlight:  37%|████████████████████████████████████████████████                                                                                   | 80138/218370 [01:24<02:22, 967.97it/s]
/usr/local/lib/python3.7/site-packages/rsatoolbox/util/inference_util.py:145: 
RuntimeWarning: invalid value encountered in multiply
  rdm_mean = np.empty((1, rdm_vector.shape[1])) * np.nan
```

FYI: Inference_util.py line 145 is in `_nan_mean()`

The behavior changes depending on the `n_jobs` setting in the call to `evaluate_models_searchlight`.

The warning never occurs if n_jobs=1. If n_jobs >1, typically 2-3 warnings will be generated but at different percent completion on each run. For example, using n_jobs=10 generated warnings at 22% complete and 40% complete on one run and then at 8%, 15%, 31%, and 62% on the next run (no changes were made to the script between runs). Other values of n_jobs (from 2-10) elicits similar behavior. 

Perhaps some bad interaction with joblib?

System Info:

• OS-X 10.14.3, Python 3.7.3, rsatoolbox 0.0.4, numpy 1.21.6, scipy 1.7.3, pandas 1.3.5, nibabel 4.0.1, joblib 1.1.0

**Comment by jones-michael-s** [comment]
Quick followup:

The line generating the warning is the following:

`rdm_mean = np.empty((1, rdm_vector.shape[1])) * np.nan
`

if you use np.random instead of np.empty to create the vector, the warning  no longer occurs:

`rdm_mean = np.random.rand(1, rdm_vector.shape[1]) * np.nan
`

(multiplying by np.nan inits the elements to nan, as in the original code).

Don't know if that tells anyone anything useful...

**Comment by JasperVanDenBosch** [comment]
Hi Michael,
Thanks for reporting this. A rework of the searchlight is in the works, but I probably won't get to to till the week of the 12th.

**Comment by HeikoSchuett** [comment]
Hi @jones-michael-s ,

Thanks for reporting this issue!
so first of all: You don't have to worry about this warning. It is really just setting the values to NaN here such that multiplying with invalid values is entirely expected. Even if it removes the warning I would not like to run the random number generation, as this is relatively slow (at least much slower than initializing and empty array).
The reason you see more warnings with joblib is that each worker throws the warning once. If you run the code with only one worker you get at most one warning and none if the same warning was already thrown earlier.

I'll have a look whether I can somehow turn off the warning or find an equally fast method that does not produce the warning.

And yes: as @ilogue writes: there is work on a better searchlight to look forward to!

**Comment by JasperVanDenBosch** [comment]
I agree with @HeikoSchuett that switching to random is not ideal, also because the presence of nans in the result would clearly indicate that something went wrong "upstream"
