### ISSUE TITLE
How to cite rsatoolbox

### ISSUE THREAD

**Issue by swasun** [rsagroup/rsatoolbox#257]
Hello,

Thank you for developing this useful package. I'd like to know if there's a preferred way to cite your package in my paper.

Best

Charly Lamothe

**Comment by JasperVanDenBosch** [comment]
Hi Charly,
Glad you found it useful!
We are working on an overview paper. In the mean time,
here is a complete list of references: https://rsatoolbox.readthedocs.io/en/latest/literature_cited.html
It's not complete, this is one of the more recent ones:

https://arxiv.org/abs/2112.09200

Basically it comes down a bit to which specific methods were important for your analysis..

**Comment by swasun** [comment]
Ty for your fast and useful answer!
