### ISSUE TITLE
Enable install through conda

### ISSUE THREAD

**Issue by HeikoSchuett** [rsagroup/rsatoolbox#258]
**Is your feature request related to a problem? Please describe.**
At the moment, the package cannot be installed through conda/anaconda because it is not available there.
Also, `petname==2.2` is not available there, but required.

**Describe the solution you'd like**
Include petname=2.2 and make a conda package to enable conda installs.

**Describe alternatives you've considered**
pip install and conda install mixed yields environments that neither method can resolve properly at some point.

**Comment by JasperVanDenBosch** [comment]
removing petname in #251

**Comment by JasperVanDenBosch** [comment]
some observations
- this is gonna require an x86 windows box
- conda-covert doesn't apply to us
- no cross-compilation

resources
- to bootstrap meta.yaml: https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html
- general guide https://python-packaging-tutorial.readthedocs.io/en/latest/conda.html
- conda-forge path https://medium.com/runic-software/simple-guide-to-conda-packages-4658cee798d6

**Comment by JasperVanDenBosch** [comment]
Submitted to the conga-forge channel at https://github.com/conda-forge/staged-recipes/pull/22230
