### ISSUE TITLE
Extracting and visualizing statistical inference

### ISSUE THREAD

**Issue by psychNerdJae** [rsagroup/rsatoolbox#264]
Thanks for the great toolbox, I've quite enjoyed using it. I have a suggestion that I think might improve the usability of the statistical inference procedures.

**Is your feature request related to a problem? Please describe.**
Once an object of class `rsatoolbox.inference.result.Result` is created, it is difficult to extract (e.g.) a table of statistics from running inferential tests. It is very straightforward to visualize these statistics using `rsatoolbox.vis.plot_model_comparison`, but I often find myself wanting direct access to the numbers. This is helpful for (e.g.) reporting the results of specific statistical tests in the text of a manuscript, or for creating custom plots highlighting key results.

Related to that second point, `plot_model_comparison` currently does not return the created figure. Therefore, while it's easy to create an inline plot of model comparisons in a jupyter notebook, it's difficult to save that plot to disk (or to customize it).

**Describe the solution you'd like**
As currently instantiated, `plot_model_comparison` is really doing the work of three functions at once: getting p-values from the relevant statistical tests (one-sample and pairwise tests), computing variance around the expectations (e.g., SEM, CI), and then plotting all of the results.

As an alternative, these operations could be refactored into two separate functions. The first new function might return a human-readable dictionary (or table) of all statistical results. To illustrate what this might look like:

```python
{
    "noise_ceil_lower": value,
    "noise_ceil_upper": value,
    "pvalue_model0_vs_0": p-value testing model0 against 0,
    "pvalue_model0_vs_model1": p-value from pairwise test of model0 against model1,
    etc...
}
```

Once this dictionary/table of results is created, it could then be passed into a new plotting function, which basically is just the plotting elements of `plot_model_comparison` shunted off into a new function. To preserve backwards compatibility and user-friendliness for those who don't want/need access to the statistics, `plot_model_comparison` might then be a thin wrapper around the two refactored functions.

**Volunteer**
- would you be willing to write code for the library with us?
- if so, what do you need from us to get started?

In principle, I would be willing to write code to address this issue. However, I should disclaim that I'm very much a software user, not a developer. I have relatively little familiarity with software development (e.g., modifying "published" libraries, writing tests, etc), and so I would need some support from developers to learn how to be an effective contributor.

**Comment by HeikoSchuett** [comment]
Hi @psychNerdJae ,
thank you for your thoughtful comments! I agree that giving the users more access to the test results is a great idea.

As the results object is already a summary of the results, I would prefer a solution that does not create another (list or dictionary) object from this one. The computations to extract the values you ask for from the results object do not take much time. They are now computed from it while creating the figure as well. Thus, I would implement this as functions of the results object.

The computations are already available as functions that are called by the plot (in /util/inference_util.py). Until I (or someone else) gets around to implementing the simpler access you can use those to get the numbers you need. Some print function for the results object would be a great addition as well.

**Comment by HeikoSchuett** [comment]
I now implemented some functions to extract the test results in a pull request. Could you check whether this does what you wanted to do?

I will remove the code duplicates from the model plot function before I merge the pull request.

**Comment by psychNerdJae** [comment]
Hi @HeikoSchuett, thanks for your quick response/implementation, and apologies for the delayed response on my end. Yes, this looks good to me! The new methods (`test_x` and `get_x`) for the Results object provide exactly the functionality I had in mind.

I think they also provide some of the functionality alluded to in [the documentation](https://rsatoolbox.readthedocs.io/en/latest/inference.html), where it's stated that "The intended use [of the results object] is to pass this object directly to visualization functions, *test function* etc. and do not need to consult the contents directly often" (emphasis mine). I wasn't previously aware of any test functions that users were meant to access, so this PR will be really helpful on that front.

Thanks again, and I'm looking forward to seeing these changes appear in v0.0.5 of this toolbox!
