### ISSUE TITLE
weighted models, searchlights and theta

### ISSUE THREAD

**Issue by nimarek** [rsagroup/rsatoolbox#265]
First of all, thank you to all the people who invest their time in this great project!

I am currently working on a whole-brain fMRI analysis using the *searchlight*, the *ModelWeighted* and the *fit_regress* functions. For each searchlight, there are 5 possible candidate RDMs from behavioral data. An evaluation using *evaluate_models_searchlight* and *ModelWeighted* already works and now I would like to optimize the evaluation by adjusting the theta parameters - but fail because of the following error message: *AssertionError: If a list of models is passed theta must be a list of parameters*. My guess: I should pass 5 times as many theta parameters to the evaluation function as I have voxels, since I have 5 possible candidate RDMs per voxel?

Following the *flexible models* tutorial (https://github.com/rsagroup/rsatoolbox/blob/main/demos/demo_flexible_models.ipynb), I only accomplished to get a list of 5 parameters (*Theta based on optimization:
[ 0.94528654  0.05222921 -0.29553073  0.11560278  0.05480007]"*) using the same fMRI data and all 5 behavioral RDMs. 

If more information (code, data) is needed, I will gladly provide it. Thanks a lot,
Nico

**Comment by HeikoSchuett** [comment]
Hi @nimarek,

sorry for the delay. The assertion indicates that you passed a single set of parameters, but multiple models. I guess, that you created 5 ModelWeighted instances for the five behavioral RDMs? If that is the case, simply passing a single ModelWeighted instance with the 5 RDMs inside should do the trick. Or are you running the evaluation through the searchlight implementation already?

In any case, the code you use to start the evaluation would be great to have!

**Comment by JasperVanDenBosch** [comment]
Closing this for now, but @nimarek if Heiko's suggestion didn't solve your issue feel free to re-open
