### ISSUE TITLE
RSA analysis using SPM betas

### ISSUE THREAD

**Issue by TamerGezici** [rsagroup/rsatoolbox#290]
Hello,

I have an event related design where I want to look at similarities for some beta estimates generated using SPM. Are there any sample scripts that I can use to do such analysis?

**Comment by JasperVanDenBosch** [comment]
Hi @TamerGezici 
Thanks for your question. We don't have an existing demo for this specific scenario,
but I reckon you basically get the beta patterns out of the file and create a `Dataset` from them.
If you can send me (japsai at gmail) a sample file, I could make an example script if you like.
-- Jasper

**Comment by JasperVanDenBosch** [comment]
I'll close this issue for now, if you have more questions feel free to re-open!
