### ISSUE TITLE
Help with negative correlations?

### ISSUE THREAD

**Issue by jones-michael-s** [rsagroup/rsatoolbox#300]
Hello,

We're run into an unexpected result in that our models consistently produce negative correlations (i.e., the bargraphs generated by eval_fixed are all pointing downward).

Our initial reaction was that our models (or our use of the toolbox) were wrong, but we can't find any mistakes in either. Indeed, if we "invert" our models to make the large distances small and the small distances large, we get positive correlations. However, we can't justify such a model modification logically.

We're rather new to RSA so I thought I would ask if anyone else has encountered this and whether there might be some standard fix (e.g., "try whitening your data", or "try this other distance metric", or "try using larger (or smaller) ROIs").

Any advice from experienced RSA users?

Thanks much,
Mike

**Comment by iancharest** [comment]
Hi Mike,

Could you tell us a little bit more about your models and data?

What kind of models are we looking at? Binary models encoding clusters in
the data? Distance matrices built from some continuous embedding space?

What metric did you use in constructing your brain rdms? Is it from fmri
data?

That would help in understanding what's going on.

ian

**Comment by nkriegeskorte** [comment]
there could be a bug somewhere.
it's true that RDMs tend to be positively correlated in practice.

note however that RDMs can be negatively correlated. here's a simple
example (blue: small dissimilarity, red: large dissimilarity)...

[image: image.png]

**Comment by jones-michael-s** [comment]
Sorry for the delayed response  (I wanted to meet with members of our group in case they had helpful information).

@iancharest 

It's fMRI data. Subjects are reading or hearing words (and sometimes repeating them) and we are examining responses in a number of visual, auditory, and motor ROI.

Our models are relatively low dimensional -- some are based on word differences quantified by a single metric while others use ~5-15 binary measures (converted into a Hamming distance).

We're using (squared) euclidean distance to construct the data RDM. We noted a few anomalous responses in the data (e.g., an excessively large beta for a particular word compared to that obtained for the other words) likely because of coincident subject motion (each word is presented only once in our task). We've tried excluding such "outliers" from the analysis, but that did not resolve the negative correlations. Everything else appears to be as it should.

@nkriegeskorte 

Thank you for the example. Although we assumed it was mathematically possible to construct a model that is negatively correlated with the data, it just seemed odd to us that all of our models currently exhibit this behavior.

As for a possible bug -- I believe the RSA toolbox is working correctly (I'm able to independently reproduce the summary bar graph generated by eval_fixed using my own Matlab code). However, there may be problems in our preprocessing, modeling, or data extraction. We will continue to explore this.

**Comment by HeikoSchuett** [comment]
If there are no more suggestions, I plan to close this issue in about a week. If you have more to say, please do so and I'll leave it open!
