### ISSUE TITLE
Getting an Average RDM from a stack of partial RDMs in Multiple Arrangements Task

### ISSUE THREAD

**Issue by arianayoum** [rsagroup/rsatoolbox#320]
Hello, I have the output from a Multiple Arrangement Task in the form of a .mat file and am unsure how I should be formatting the data such that I can use the from_partials function.

**Comment by JasperVanDenBosch** [comment]
Hi Ariana,

First you have to make the RDMs object that this library uses to represent dissimilarity matrices. One way is to try the built-in `load_rdms` (see [docs here](https://rsatoolbox.readthedocs.io/en/stable/rsatoolbox.io.meadows.html#rsatoolbox.io.meadows.load_rdms))

```python
from rsatoolbox.io.meadows import load_rdms
rdms = load_rdms('/path/to/my.mat')
```

Alternatively you could do step by step, roughly like this:

```python
from scipy.io import loadmat
from rsatoolbox.rdm.rdms import RDMs
data = loadmat('/path/to/my.mat')
rdms = RDMs(
    dissimilarities=data['rdmutv'],
    pattern_descriptors=dict(stimulus=data['stimuli'])
)
```

After that you'd pretty much follow the steps in [this guide](https://rsatoolbox.readthedocs.io/en/stable/rescale_partials.html). 
Hope this helps

**Comment by arianayoum** [comment]
Hi,

Thank you for your response! It works with the load_rms function :) 

Cheers,

Ariana

**Comment by JasperVanDenBosch** [comment]
Excellent! I'll close this issue, but feel free to post a new one if you have another question
