### ISSUE TITLE
Minimal changes to `get_searchlight_RDMs` to make it more convenient

### ISSUE THREAD

**Issue by mathias-sm** [rsagroup/rsatoolbox#329]
`get_searchlight_RDMs` is very convenient when working with fMRI datasets, but a few small changes would make it easier for me to use, and might benefit others. As things stand, I basically wrote my own version of it, which is almost 100% identical to upstream. I am aware of the efforts in PR #253 whence this issue instead of a PR with my small changes.

There are two things that I would happily add because I use/need them:

* `calc_rdm` takes more arguments than `get_searchlight_RDMs` does, making the later less flexible than the former, e.g. I needed to pass a `cv_descriptor` when using `crossnobis` distance, but `get_searchlight_RDMs` cannot handle that. Same with `noise`, `prior_lambda` and `prior_weight`. Adding them to `get_searchlight_RDMs` could be useful, possibly with `**kwargs`?
* Parallelizing over `chunks` seems easy and reasonable, esp. as the searchlight util functions already make use of joblib's parallel. I did it by turning `for chunks in tqdm(chunked_center, desc='Calculating RDMs...'):` into a function like `def chunk_to_rdm(chunk):`, then called with `RDM_corrs = Parallel(n_jobs=-1)(delayed(chunk_to_rdm)(chunk) for chunk in track(chunked_center))` followed by

```python
for chunks, RDM_corr in zip(chunked_center, RDM_corrs):
    RDM[chunks, :] = RDM_corr.dissimilarities
```
 
I'd be happy to add these two changes (I have already added them locally to what I'm running, but this makes sharing my code with others harder), and would happily upstream them if it's considered useful.

**Comment by CompSocNeuroGroup** [comment]
Hi @mathias-sm did you get any response here? I've been struggling with trying to get a `crossnobis` searchlight working, and was wondering if you'd be willing to share your version `get_searchlight_RDMs` that you can pass `noise` to? thx

**Comment by JasperVanDenBosch** [comment]
Just an update from our side here; both these features are planned as part of a larger rework of searchlights, but we don't have time in the next month or two as we're prioritising other features. So if @mathias-sm can share his code that may be the best approach in the short run.

**Comment by hippocampeli** [comment]
I just followed @mathias-sm proposal.  The code worked for me and decreased computation time significantly. Thx!

```
def chunk2rdm(data_2d,events,chunk,centers,neighbors, method):
    center_data = []
    for c in chunk:
        # grab this center and neighbors
        center = centers[c]
        center_neighbors = neighbors[c]
        # create a database object with this data
        ds = Dataset(data_2d[:, center_neighbors],
                     descriptors={'center': center},
                     obs_descriptors={'events': events},
                     channel_descriptors={'voxels': center_neighbors})
        center_data.append(ds)
        
    RDM_corr = calc_rdm(center_data, method=method,
                        descriptor='events')
    return RDM_corr
```
Then i replaced the "for chunks in ..." in the original function with parallel execution of the chunk2rdm function like so:
```
RDM_corrs = Parallel(n_jobs=n_jobs)(delayed(chunk2rdm)(data_2d,events,chunk,centers, neighbors, method) for chunk in tqdm(chunked_center))
        
for chunks, RDM_corr in zip(chunked_center, RDM_corrs):
    RDM[chunks, :] = RDM_corr.dissimilarities
```

**Comment by mathias-sm** [comment]
Hi,

Thanks for the replies.  Somehow I missed notifications about this issue. @hippocampeli effectively ended up writing almost exactly the same code as mine — which, just in case someone finds it useful, I'm putting below.

```python
n_centers = centers.shape[0]
chunked_center = np.split(np.arange(n_centers), np.linspace(0, n_centers, 101, dtype=int)[1:-1])

def map_one(chunks, method, descriptor, cv_descriptor):
    center_data = []
    for c in chunks:
        center = centers[c]
        center_neighbors = neighbors[c]
        ds = Dataset(
            data_2d[:, center_neighbors],
            descriptors={"center": center},
            obs_descriptors=obs_descriptors,
            channel_descriptors={"voxels": center_neighbors},
        )
        center_data.append(ds)

    return calc_rdm(center_data, method=method, descriptor=descriptor, cv_descriptor=cv_descriptor)

# map; send parallel computation over several jobs
RDM_corrs = Parallel(n_jobs=10)(delayed(map_one)(c, method, descriptor, cv_descriptor) for c in track(chunked_center))

# reduce; take the result of the parallel computations and stitch them back together
n_conds = len(np.unique(obs_descriptors[descriptor]))
RDM = np.zeros((n_centers, n_conds * (n_conds - 1) // 2))
for chunks, RDM_corr in zip(chunked_center, RDM_corrs):
    RDM[chunks, :] = RDM_corr.dissimilarities
```

There's still a more general solution based on `**kwargs` lurking somewhere, but this works.

**Comment by sanghoon-kang** [comment]
Hi all,

I’ve been running manual crossnobis searchlight analyses in Python (using rsatoolbox), and wanted to ask if others have run into issues with fold-level precision estimation — i.e., estimating a precision matrix per CV fold and passing that to calc_rdm_crossnobis.

I’m doing something like this:
```
def build_fold_precisions(ds, fold_key, obs_desc='all', method='shrinkage_diag'):
    """
    Per-fold precision estimates for crossnobis RDMs.
    Falls back to identity when estimation fails or returns invalid values.
    """
    import numpy as np
    from rsatoolbox.data.noise import prec_from_measurements

    folds = np.asarray(ds.obs_descriptors[fold_key])
    uniq  = np.unique(folds)
    P_list = []
    invalid_precision_count = 0

    n_obs, n_chan = ds.measurements.shape

    for held in uniq:
        # Train on all folds except the held one
        ds_train = ds.subset_obs(fold_key, [f for f in uniq if f != held])

        # Build dataset for pooled noise estimation
        if obs_desc == 'all':
            dsn = ds_train.copy()
            dsn.obs_descriptors = dict(dsn.obs_descriptors)
            n_train = dsn.measurements.shape[0]
            dsn.obs_descriptors['all'] = np.ones(n_train, dtype=int)
            target, key = dsn, 'all'
        else:
            target, key = ds_train, obs_desc

        # Default to identity in case estimation fails
        P = np.eye(n_chan, dtype=float)

        try:
            P_est = prec_from_measurements([target], obs_desc=key, method=method)[0]
            if P_est.shape == (n_chan, n_chan) and np.isfinite(P_est).all():
                P = P_est
            else:
                invalid_precision_count += 1
        except Exception:
            invalid_precision_count += 1

        P_list.append(P)

    return P_list, invalid_precision_count
```
After running this inside a searchlight, and then passing the noise list to `rdm = calc_rdm_crossnobis(ds, descriptor = "conditions", cv_descriptor=cv_key, noise=noise_list, remove_mean=True)`, I get some whole brain results that I couldn’t quite understand:

1. Some subjects have a very high proportion of invalid precision estimations (where I fallback to identity; up to around 30% ofa all estimations).


2. Their crossnobis maps are largely empty subcortically (example image below).


3. The issue seems to get worse with larger searchlight radii.


Would really appreciate any insight, or examples of stable fold-level precision estimation strategies with rsatoolbox.
I can share my searchlight code if it helps; it uses fold-wise precision replacement and counts invalid estimates per patch.


<img width="763" height="385" alt="Image" src="https://github.com/user-attachments/assets/fd1fcc3d-7407-4e94-b438-e5a459c82f20" />
