### ISSUE TITLE
add CITATION.cff to repository

### ISSUE THREAD

**Issue by andreifoldes** [rsagroup/rsatoolbox#333]
**Describe the solution you'd like**
I'd like to cite this repository in my thesis and saw that is a cool way to cite repositories if they contain a CITATION.cff file.
https://github.blog/2021-08-19-enhanced-support-citations-github/

**Describe alternatives you've considered**
Currently I cited it like this:
@software{represen2023,
	title = {Representational Similarity Analysis 3.0},
	year = {2023},
	month = {07},
	date = {2023-07-19},
	publisher = {RSA development group},
	url = {https://github.com/rsagroup/rsatoolbox},
	note = {original-date: 2019-10-07T02:08:28Z}
}

**Comment by JasperVanDenBosch** [comment]
Thanks Andrei! This is a great suggestion. Let me talk to some of the others and we'll add this some time next week. For now your citation makes sense!

**Comment by caiw** [comment]
I've also just started a short project which will make use of the toolbox; it'd be cool to cite it in the resultant report.

**Comment by shawnrhoads** [comment]
I would also love to cite this toolbox for an upcoming manuscript! Following this issue thread in case there is any movement!

**Comment by caiw** [comment]
Apologies if this touches on an existing conversation of which I'm not aware, but I just typed out a citation as:
"_Representational Similarity Analysis 3.0 (Version 0.1.5) [Computer software]_", and wondered if this was a confusing mixture of naming and semantic version numbering.

**Comment by JasperVanDenBosch** [comment]
> Apologies if this touches on an existing conversation of which I'm not aware, but I just typed out a citation as: "_Representational Similarity Analysis 3.0 (Version 0.1.5) [Computer software]_", and wondered if this was a confusing mixture of naming and semantic version numbering.

Yeah it's a good point. I think some of us have discussed this in the past but didn't come up with a great solution. I think the options are:
1. Keep the mix
2. Adapt the versions, to continue at 3.0.1 etc
3. Change the title.

But basically these each have downsides. To be fair this should go away when the paper becomes citable as then you wouldn't use the library version in the citation.
