### ISSUE TITLE
'RDMs.sort_by' sorting is not stable

### ISSUE THREAD

**Issue by caiw** [rsagroup/rsatoolbox#374]
Not sure if this is a bug-report, as I'd argue the current behaviour is unexpected, or if it's just an enhancement request.

The sorting algorithm used in `RDMs.sort_by` is not [stable](https://en.wikipedia.org/wiki/Sorting_algorithm#Stability), i.e. equal elements aren't guaranteed to have their order preserved.  By contrast, Python's `sorted()` is stable.  I'm not sure about numpy, but presumably it's not because I think that's what `sort_by` is using.

## Why one would care about stability

Suppose we have a `pattern_descriptor` called "object" which stores a string name of image photos shown to participants, and a second `pattern_descriptor` called "category" which stores a string name of one of 5 object categories relating the the image.  So the "object" `pattern_descriptor` might store "alligator", "giraffe", "daisy", "rose", etc. for 4 conditions; and the "category" `pattern_descriptor` might store "animal", "animal", "flower", "flower" for the same 4 conditions.

Suppose I want to order the conditions in the RDM so that all animals appear at the top, then all flowers, etc.  And within each category block, the items to be ordered alphabetically.  So for the above 4 conditions this should be:
- [animal] alligator
- [animal] giraffe
- [flower] daisy
- [flower] rose
etc.

My expected way to do this is a 2-level sort like:

```python
rdms.sort_by(**{"object": "alpha"})  # Now all the objects are in alpha order by the categories are jumbled
rdms.sort_by(**{"category": "alpha"})  # Now all the categories are in alpha order, and where there are ties (same category) the previous sort is preserved
```

However this doesn't (always) work.
## How to workaround it

Currently I'm using the folliwing few helper functions:

```python
def argsort(seq):
    """Pure python argsort"""
    # Thanks https://stackoverflow.com/a/57028877/2883198
    return sorted(range(len(seq)), key=seq.__getitem__)

def reset_pattern_index(rdms: RDMs):
    """Resets rdms.pattern_descriptors["index"] in place."""
    rdms.pattern_descriptors["index"] = list(range(rdms.n_cond))

def sort_bys(rdms: RDMs, pattern_descriptors: tuple[str, ...], reindex: bool = True):
    """Sort by each of the pattern_descriptors, alpha order, in order (i.e. ties in the first resolved by the second, etc.)"""
    sorting_data = list(zip(*(rdms.pattern_descriptors[d] for d in pattern_descriptors)))
    idxs = argsort(sorting_data)
    rdms.sort_by(**{"index": idxs})
    if reindex:
        reset_pattern_index(rdms)

# Use like
sort_bys(rdms, pattern_descriptors=("category", "object"))
```
 
(As you can see, part of the above is also my workaround for #358)

I'm dropping the above here because I wonder if these multi-level sorts could also be incorporated into `sort_by`, which currently has (to my eye) a slightly strange interface.

**Comment by caiw** [comment]
Ah, it looks like numpy now [lets you specify that the sort should be stable](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html#:~:text=The%20‘stable’%20option%20was%20added.), so this would be a simple fix.

**Comment by JasperVanDenBosch** [comment]
If using the stable option with numpy would fix it, that sounds good. I assume the performance isn't a major concern here. (timsort probably does well enough for us)
