### ISSUE TITLE
is the library compatible with ARM-64 architecture?

### ISSUE THREAD

**Issue by eghbalhosseini** [rsagroup/rsatoolbox#383]
I have install the toolbox from source but when I try to import rsatoolbox I get the following error : 
`ImportError: dlopen(.../rsatoolbox/src/rsatoolbox/cengine/similarity.cpython-39-darwin.so, 0x0002): tried: '.../rsatoolbox/src/rsatoolbox/cengine/similarity.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
  File "<stdin>", line 1
    ImportError: dlopen(.../rsatoolbox/src/rsatoolbox/cengine/similarity.cpython-39-darwin.so, 0x0002): tried: '.../rsatoolbox/src/rsatoolbox/cengine/similarity.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')),`

I have macbook M3 version , and have tried installing it using pip, or pip install -e .

**Comment by JasperVanDenBosch** [comment]
It looks like you may be running this in a compatibility mode, like Rosetta? I'm on an M1 myself and it compiles without any further config. What terminal are you using?

**Comment by eghbalhosseini** [comment]
I think it is fixed now, I had to use mac base terminal and install it with the following options 
pip install rsatoolbox --ignore-installed --no-cache-dir

Thank you for your help :)
