### ISSUE TITLE
alternative to np.corrcoef for correlation distance

### ISSUE THREAD

**Issue by iancharest** [rsagroup/rsatoolbox#39]
Hi @HeikoSchuett ,

given that we use einsum for all other RDM calc cases, I figured we could also use it for correlation distance. that speeds up performance massively compared to numpy corrcoef.

```python
def correlation_distance(X):
    """[correlation distance]

    Args:
        X ([dataset]): conditions x voxels dataset

    Returns:
        RDM in upper triangular form.        
    """
    X = X - X.mean(axis=1, keepdims=True)
    X /= np.sqrt(np.einsum('ij,ij->i', X, X))[:, None]

    m = X.shape[0]
    r, c = np.triu_indices(m, 1)
     
    return 1 - np.einsum('ik,jk', X, X))[r, c]
```

**Comment by HeikoSchuett** [comment]
Hi Ian,
sounds very sensible. We could then use the numpy implementation as the test in parallel to the euclidean implementation. 
Could you start this as a pull request with the new implementation of the correlation distance build in?
