### ISSUE TITLE
add function to plot images into axis

### ISSUE THREAD

**Issue by HeikoSchuett** [rsagroup/rsatoolbox#72]
should allow:
transparancy & circular aperture
size regulation
colored border
strings as replacements

**Comment by iancharest** [comment]
I think Jasper had started such a function a while back...

**Comment by HeikoSchuett** [comment]
If you have a starting point for this lying around please share it of course

**Comment by iancharest** [comment]
https://github.com/Charestlab/pyrsa/blob/master/pyrsa/graphics/imagesAsTickMarks.py

Not sure what state this is in...

**Comment by jooh** [comment]
I have something that works, but bumped into issues with bugs in Matplotlib auto cropping of figure limits last time I played with it:

https://github.com/jooh/sana/blob/503ceae47734fb047f7ecd4b0dc03763b05a49dd/sana/plot.py#L8-L76

Example output here:

https://github.com/matplotlib/matplotlib/issues/12699#issuecomment-435340497

**Comment by HeikoSchuett** [comment]
Was included in form of the Icon object
