### ISSUE TITLE
API reference doc contains link to non existing autodoc stub for pyrsa.simulation.sim

### ISSUE THREAD

**Issue by JasperVanDenBosch** [rsagroup/rsatoolbox#81]
Compiling the docs returns this:
```
pyrsa/docs/source/pyrsa.rst:65: WARNING: toctree contains reference to nonexisting document 'pyrsa.simulation.sim'
```

**Comment by jdiedrichsen** [comment]
For now removed simulation.sim from documentation, as the module never made it into Master. 
What is the status of the simulation functionality (sim_dev)?

**Comment by HeikoSchuett** [comment]
Hi Jörn, I think the status of the simulation code is that it is in principle functional, but requires a bit of clean up to pass code review and a bit more explanation what is going on such that things are understandable. Do you maybe have the time to add these explanations?
