### ISSUE TITLE
Covariance matrix for Crossnobis dissimilarity

### ISSUE THREAD

**Issue by charlesbmi** [rsagroup/rsatoolbox#83]
I was looking at https://rsa3.readthedocs.io/en/latest/distances.html#crossnobis-dissimilarity , and noticed that the covariance matrix is not included.

Shouldn't the covariance matrix be included in a cross-validated Mahalanobis distance, too? https://en.wikipedia.org/wiki/Mahalanobis_distance

Not sure what this would look like in a cross-validated version.

**Comment by HeikoSchuett** [comment]
This is purely a documentation issue, the crossnobis distance does indeed contain a reweighting with the precision matrix just as the Mahalanobis distance. This is also implemented in pyrsa.rdm.calc_*

**Comment by charlesbmi** [comment]
got it, thanks!
