### ISSUE TITLE
get_unique_unsorted() in data_utils.py resorts data incorrectly

### ISSUE THREAD

**Issue by adkipnis** [rsagroup/rsatoolbox#84]
The code should be:
```
def get_unique_unsorted(array):
    """return a unique unsorted list
    """
    u, indices = np.unique(array, return_index=True)
    temp = indices.argsort()
    return u[temp]
```
Otherwise the initial order of observation descriptors does not get restored.

**Comment by HeikoSchuett** [comment]
Hi @adkipnis,

could you make a pull request with this code change and a test which fails for the current version?

**Comment by doerlbh** [comment]
This is a good observation, Alex. I just checked and approved your PR https://github.com/rsagroup/pyrsa/pull/85. Now it has two approvals. Can someone with authorization merge it? BTW, can I be granted the access to merge as well? Thanks!
