### ISSUE TITLE
fMRI data to pyrsa

### ISSUE THREAD

**Issue by AdrianLeon51** [rsagroup/rsatoolbox#89]
Hi,

In order to define our data set, could you please provide us with a step-by-step for how to import fMRI data an put it in the right format for the toolbox?

**Comment by HeikoSchuett** [comment]
I am sure we will have such an example relatively soon, yes.

**Comment by adkipnis** [comment]
@AdrianLeon51 in case you have nifti images as SPM output, you might find something useful in my repo:
https://github.com/adkipnis/fmri-simulations

We will work on code for importing fMRI data and pooling it into PyRSA datasets soon.

**Comment by limbicode214** [comment]
also very interested in this. Still have no easy way to convert my fMRI data (nii-files, 20 conditions, 2 runs with 120 stimuli) into the mat-structure for the rsatoolbox. Any help would be greatly appreciated!
