### ISSUE TITLE
fix RDMs.sort_by()

### ISSUE THREAD

**Issue by JasperVanDenBosch** [rsagroup/rsatoolbox#96]
The current version refers to a property called `measurements` which does not seem to be in use.

And when this is removed it is unclear how the following line:

```
dissimilarities[:, order][:, :, order]
```

would sort the pattern order

**Comment by HeikoSchuett** [comment]
this measurements thing is indeed odd.
the line you refer to I think is correct though. There is a stack of matrices. the first subsetting reorders the rows, the second the columns.

**Comment by JasperVanDenBosch** [comment]
It seems to come out with an extra dimension

**Comment by HeikoSchuett** [comment]
ah yes, I just checked: the line below this should be:
self.dissimilarities = batch_to_vectors(dissimilarities)[0]
instead of 
self.dissimilarities = batch_to_vectors(dissimilarities)


Sorry for this not working properly

**Comment by JasperVanDenBosch** [comment]
no worries I'm making a test now and I'll commit to #78
